# Default values for onezone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

redis:
  persistence:
    enabled: false
  resources:
    requests:
      memory: 250Mi
      cpu: 10m

redis-1:
  persistence:
    enabled: false
  resources:
    requests:
      memory: 251Mi
      cpu: 11m

redis-2:
  persistence:
    enabled: false
  resources:
    requests:
      memory: 252Mi
      cpu: 12m